# ANALOGY 模型超参数搜索
# 2025/10/28 创建

project: 'kg4rd'
sweep_name: 'ANALOGY_base_hpo_20251028'

in_path: 'src/kg4rd/kge/data/'
train_file: 'train2id_base.txt'
valid_file: 'valid2id_base.txt'
test_file: 'test2id_base.txt'

device_trainer: "cuda:1"
device_tester: "cuda:1"

test_batch_size: 5

log_interval: 1
valid_interval: 50
save_path: "src/kg4rd/kge/checkpoints/ANALOGY_base_hpo_20251028/model.pth"
epochs: 1000

hpo_hits: [1, 3, 10, 30, 50]