# 多 GPU 训练评估 TransE 模型, 在补充后的整个图谱上训练
# 2025/09/09 创建, 参照之前超参数调优的结果

project: 'kg4rd'
name: 'transe_eval_gpus_20250909'

in_path: 'src/kg4rd/kge/data/'
train_file: 'train2id.txt'
valid_file: 'valid2id.txt'
test_file: 'test2id.txt'

batch_size: 500
neg_ent: 64
num_workers: 16
dim: 200
p_norm: 1
norm_flag: True
margin: 1.0
epochs: 1000
lr: 0.6
adv_temperature: 3.0
opt_method: "SGD"

test: True
test_batch_size: 10
test_use_gpu: True
test_hits: [1, 3, 10, 30, 50]

train_use_gpu: False
use_accelerator: True
delta: 0.01
use_early_stopping: True

device: "cuda:0"

valid_interval: 50
log_interval: 1
save_interval: 50
save_path: "src/kg4rd/kge/checkpoints/transe_eval_gpus_0909.pth"
