project: 'kg4rd'
name: 'TransE_eval_Accel_20250910'

in_path: 'src/kg4rd/kge/data/'
train_file: 'train2id.txt'
valid_file: 'valid2id.txt'
test_file: 'test2id.txt'

batch_size: 4096
neg_ent: 64
num_workers: 16
dim: 200
p_norm: 1
norm_flag: True
margin: 1.0
epochs: 500
lr: 0.05079633914318759
adv_temperature: 6.0
opt_method: "adam"

test_batch_size: 10
tester_use_gpu: True
test_hits: [1, 3, 10, 30, 50]
tester_device: "cuda:2"

trainer_device: "cuda:2"
use_accelerator: False
delta: 0.01
use_early_stopping: True

valid_interval: 50
log_interval: 1
save_interval: 100
save_path: "src/kg4rd/kge/checkpoints/TransE_eval_Accel_20250910.pth"
