project: 'kg4rd'
name: 'TransE_entrie_Accel_20250910'

in_path: 'src/kg4rd/kge/data/'
train_file: 'all2id.txt'

batch_size: 4096
neg_ent: 64
num_workers: 16
dim: 200
p_norm: 1
norm_flag: True
margin: 1.0
epochs: 1000
lr: 0.05079633914318759
adv_temperature: 6.0
opt_method: "adam"

trainer_use_gpu: True
trainer_device: "cuda:0"
use_accelerator: False
delta: 0.01

log_interval: 1
save_interval: 50
save_path: "src/kg4rd/kge/checkpoints/TransE_entrie_Accel_20250910.pth"
