# TransE 模型超参数搜索
# 使用 GCL 训练得到节点预嵌入
# 2025/11/02 创建

project: 'kg4rd'
sweep_name: 'TransE_PreEv2_hpo_20251102'

in_path: 'src/kg4rd/kge/data/'

device_trainer: "cuda:0"
device_tester: "cuda:0"

test_batch_size: 20
batch_size: [128, 256, 512, 1024, 2048, 4096]

dim: 256

log_interval: 1
valid_interval: 50
save_path: "src/kg4rd/kge/checkpoints/TransE_PreEv2_hpo_20251102.pth"
epochs: 1000

hpo_hits: [1, 3, 10, 30, 50, 100]

ent_embed_path: "src/kg4rd/gcl/embeddings/gcl_20251014/ent_embed.npz"